version: '3'
services:
  app:
    env_file:
      - .env
    container_name: blog
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    env_file:
      - .env

volumes:
  pgdata:
